### ISSUE TITLE
enhancement: stringified coordinates should be coerced to numbers

### ISSUE THREAD

**Issue by ungoldman** [Esri/terraformer-arcgis-parser#29]
Trying this:

```js
//parse an ArcGIS Geometry to GeoJSON
var point = Terraformer.ArcGIS.parse({
  x:"-122.6764",
  y:"45.5165",
  spatialReference: {
    wkid: 4326
  }
});
```

One gets an error such as this:

```
Error: Unknown type: undefined
    at new Primitive (/Users/nate/dev/lab/sandbox/node_modules/terraformer/terraformer.js:645:15)
    at Object.parse (/Users/nate/dev/lab/sandbox/node_modules/terraformer-arcgis-parser/terraformer-arcgis-parser.js:291:12)
```

**Comment by tsamaya** [comment]
I have made a PR #27 to change the example on the readme.md

**Comment by ngoldman** [comment]
This issue is nearing a one year anniversary! @patrickarlt :wave: --> #27

**Comment by tsamaya** [comment]
:smile: 
it is only a readme :smiley:
